spring.application.name=naming-server


server.port=8761

### configure an application not to both register itself with Eureka or fetch the registry of other services.
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false