spring.application.name=limits-service

server.port=8081
limits-service.minimum=30
limits-service.maximum=235

## Spring Cloud Configuration
## if you don't add the below config in case you already and the config client depenecy project will not run [No spring.config.import property has been defined]
spring.config.import=optional:configserver:http://localhost:8888

spring.profile.active=dev
spring.cloud.config.profile=dev