spring.application.name=spring-cloud-config-server


server.port=8888
## /// will get the file from the repo
spring.cloud.config.server.git.uri= https://github.com/minaSamy1/SpringCloudConfiguration.git
spring.cloud.config.server.git.clone-on-start=true


## Testing the Config server get the configuration or Not [ localhost:8888/limits-service/default]
